{% set name = "apache-airflow-providers-apache-livy" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_livy-{{ version }}.tar.gz
  sha256: ce45c6ae35dcfe18dd3514e01864900d4437deacbf70f2b201680190d0ebc8ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.10.0
    - apache-airflow-providers-http >=5.1.0
    - apache-airflow-providers-common-compat >=1.5.0
    - aiohttp >=3.9.2
    - asgiref >=2.3.0

test:
  imports:
    - airflow.providers.apache.livy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-livy for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apache/livy/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-livy/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
