{% set name = "apache-airflow-providers-apache-livy" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-livy-{{ version }}.tar.gz
  sha256: 8bf9de310a4c70ae244f5453c1f53600164fe8fbc10658f5ec66705e8cb3839b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
    - setuptools
  run:
    - python >=3.8
    - aiohttp
    - apache-airflow-providers-http
    - apache-airflow >=2.4.0
    - asgiref

test:
  imports:
    - airflow.providers.apache.livy
    - airflow.providers.apache.livy.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-livy package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-livy/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
