{% set name = "apache-airflow-providers-apache-livy" %}
{% set version = "3.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_livy-{{ version }}.tar.gz
  sha256: bcd913f366137bc1ad854d798e482e598a94b54215d522c24f4ff6d126612681

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.9.2
    - apache-airflow-providers-http
    - apache-airflow >=2.8.0
    - asgiref >=2.3.0

test:
  imports:
    - airflow.providers.apache.livy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-livy for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/livy/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-livy/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
